name: Build WASM and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get dependencies
      run: |
        go mod tidy
        if [ -f go.sum ]; then
          git add go.sum
        fi

    - name: Build WASM
      run: |
        env GOOS=js GOARCH=wasm go build -o game.wasm shuflduf.xyz/tetr.go
        cp $(go env GOROOT)/misc/wasm/wasm_exec.js .

    - name: Clean working directory
      run: git clean -fdx

    - name: Deploy to web branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin web
        git checkout web
        git add game.wasm wasm_exec.js
        git commit -m 'Deploy WASM build'
        git push origin web --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
